//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ads.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.SubCategories = new HashSet<Category>();
            this.Ads = new HashSet<Ad>();
        }

        public string AttDefXML { get; set; }
        public string DisplayValue { get; set; }
        public Nullable<int> ParentCategoryId { get; set; }

        public virtual ICollection<Ad> Ads { get; set; }
        public virtual ICollection<Category> SubCategories { get; set; }
        public virtual Category ParentCategory { get; set; }
    }
}
