//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Ads.Model.Entities
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(CategoryMetaData))]
    public partial class Category : BaseEntity<int,int>
    {
    
    }

    public class CategoryMetaData
    {
        public object Id { get; set; }
        public object AttDefXML { get; set; }
    }
}
